---
title: "WNBA EDA Project"
output: html_document
date: "2024-06-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
library(wehoop)
library(sportyR)
library(paletteer)
library(shiny)
```



```{r}
wnba_pbp <- load_wnba_pbp(2023)
wnba_shots <- wnba_pbp |> 
  filter(shooting_play) |> 
  # make a column to indicate the shooting team
  mutate(shooting_team = ifelse(team_id == home_team_id, 
                                home_team_name,
                                away_team_name)) |> 
  select(game_id, game_play_number, game_type = season_type,
         desc = text, shot_type = type_text, 
         made_shot = scoring_play, shot_value = score_value, 
         coordinate_x, coordinate_y, shooting_team, 
         home_team_name, away_team_name, home_score, away_score, qtr,
         quarter_seconds_remaining = start_quarter_seconds_remaining,
         game_seconds_remaining = start_game_seconds_remaining)

wnba_shots <- wnba_shots |> 
  filter(shooting_team %in% c("Seattle", "Chicago", "Washington", "Atlanta", "Minnesota", "Indiana", "Los Angeles", "Connecticut", "Dallas", "Phoenix", "New York", "Las Vegas")) |> 
  mutate(made_shot = ifelse(made_shot == "TRUE", 1, 0)) |> 
  mutate(
    # take the absolute value of the x coordinate to only get one side of the court
    coordinate_x = abs(coordinate_x),
    # rename shooting_team to include team name
    shooting_team = case_match(
      shooting_team,
      "Atlanta" ~ "Atlanta Dream",
      "Chicago" ~ "Chicago Sky",
      "Connecticut" ~ "Connecticut Sun",
      "Dallas" ~ "Dallas Wings",
      "Indiana" ~ "Indiana Fever",
      "Las Vegas" ~ "Las Vegas Aces",
      "Los Angeles" ~ "Los Angeles Spark",
      "Minnesota" ~ "Minnesota Lynx",
      "New York" ~ "New York Liberty",
      "Phoenix" ~ "Phoenix Mercury",
      "Seattle" ~ "Seattle Storm",
      "Washington" ~ "Washington Mystics"
    ),
    shooter = ifelse(
      str_detect(desc, "blocks") == TRUE,
      sub(
        ".*?\\b(?:blocks)\\W+(\\w+(?:\\W+\\w+){0,2})\\b(?:'s| 's| B. 's)\\s.*",
        "\\1",
        desc,
        perl = TRUE
      ),
      sub("\\ makes.*|\\ misses.*|\\ B. makes.*|\\ B. misses.*", "\\1", desc)
    )
  )


color_vector <- c("Atlanta Dream" = "#C8102E", "Chicago Sky" = "#418FDE", "Connecticut Sun" = "#643335", "Dallas Wings" = "#C4D600", "Indiana Fever" = "#FFCD00", "Las Vegas Aces" = "#000000", "Los Angeles Spark" = "#702F8A", "Minnesota Lynx" = "#236192", "New York Liberty" = "#003DA5", "Phoenix Mercury" = "#CB6015", "Seattle Storm" = "#2C5234", "Washington Mystics" = "#0C2340")


wnba_shots <- wnba_shots[!grepl('Free Throw', wnba_shots$shot_type),]

# shot_chart <- wnba_shotchartdetail()
# 
# shot_chart <- shot_chart$Shot_Chart_Detail

```



```{r}
wnba_shots |>   
  # filter(game_type == 3) |> 
  group_by(shooting_team) |> 
  summarise(total_shot_value = sum(shot_value)) |> 
  filter(total_shot_value >= 1000) |> 
  mutate(shooting_team = fct_reorder(shooting_team, total_shot_value)) |> 
  ggplot(aes(y = shooting_team, x = total_shot_value)) +
  geom_col(aes(fill = shooting_team)) +
  theme_bw() + 
  geom_label(aes(label = total_shot_value), size = 4, fontface = "bold") + 
  scale_fill_manual(values = color_vector) +
  labs(
    title = "New York and Vegas Scoring More",
    x = "Total Points Scored", 
    y = "Teams",
    fill = "Teams",
    caption = "Data Courtesy of Wehoop"
  ) + 
  theme(#axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text.x = element_text(size = 10, vjust = 0.65),
        axis.text.y = element_text(size = 10), 
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 15))
```






```{r}

wnba_shots |> 
  filter(game_type == 2) |> 
  group_by(shooting_team) |> 
  summarise(freq = n(),
    total_shots_made = sum(made_shot)) |> 
  mutate(prop = round(total_shots_made / freq, 3),
    shooting_team = fct_reorder(shooting_team, prop)) |> 
  ggplot(aes(y = shooting_team, x = prop)) +
  geom_col(aes(fill = shooting_team)) +
  scale_fill_manual(values = color_vector) +
  theme_bw() +
  geom_label(aes(label = prop), size = 4, fontface = "bold") +
  labs(
    title = "Shooting Percentage in Regular Season",
    x = "Shooting Percentage",
    y = "Teams",
    fill = "Teams",
    caption = "Data Courtesy of Wehoop"
  ) +
  theme(#axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5, face = "bold"), 
        axis.text.x = element_text(size = 10, vjust = 0.65),
        axis.text.y = element_text(size = 10), 
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 15))
```



```{r}

wnba_shots |> 
  filter(game_type == 3) |> 
  group_by(shooting_team) |> 
  summarise(freq = n(),
    total_shots_made = sum(made_shot)) |> 
  mutate(prop = round(total_shots_made / freq, 3),
    shooting_team = fct_reorder(shooting_team, prop)) |>
  ggplot(aes(y = shooting_team, x = prop)) +
  geom_col(aes(fill = shooting_team)) +
  scale_fill_manual(values = color_vector) +
  theme_bw() +
  geom_label(aes(label = prop), size = 4, fontface = "bold") +
  labs(
    title = "",
    x = "Shooting Percentage",
    y = "Teams",
    fill = "Teams",
    caption = "Data Courtesy of Wehoop"
  ) + 
  theme(#axis.text.x=element_blank(),
        #axis.ticks.x=element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5, face = "bold"), 
        axis.text.x = element_text(size = 10, vjust = 0.65),
        axis.text.y = element_text(size = 10), 
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 15))
```



## Playoff Shooting Percentages by Player



```{r}
playoff1 <- wnba_shots |> 
  select(game_type, made_shot, shooter, shot_value) |> 
  filter(game_type == 3) |> 
  group_by(shooter) |> 
  summarise(freq = n(),
    total_shots_made = sum(made_shot),
    total_points = sum(shot_value)) |> 
  mutate(prop = round(total_shots_made / freq, 3))
  

playoff1 |> 
  filter(freq >= 18, prop > 0.5) |> 
  arrange(desc(prop)) |> 
  head(n = 10) |> 
  ggplot(aes(y = reorder(shooter, prop), x = prop)) +
  geom_col(fill = "#E77500") +
  theme_bw() +
  geom_label(aes(label = prop), size = 4, label.size = 0.5, fontface = "bold") +
  geom_text(aes(label = freq), x = 0.03, fontface = "bold") +
  geom_text(label = "shots", x = 0.08, fontface = "bold") +
  labs(
    title = "",
    x = "Shooting Percentage",
    y = "Player",
    caption = "Minimum of 18 shot attempts
    
    Data Courtesy of Wehoop"
  ) +
  theme(plot.title = element_text(hjust = 0.5, face= "bold"),
        axis.text.x = element_text(size = 10, vjust = 0.65),
        axis.text.y = element_text(size = 10), 
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 15))



# wnba_shots |> 
#   filter(game_type == 3) |> 
#   group_by(shooter) |> 
#   summarise(total_shots = n(),
#             total_made = sum(made_shot),
#             total_points = sum(shot_value)) |> 
#   mutate(shooting_perc = total_made / total_shots,
#          points_per_shot = total_points / total_shots) |> 
#   filter(total_shots >= 18)
```



```{r}
playoff1 |> 
  filter(freq >= 18, prop < 0.4) |> 
  arrange(prop) |> 
  head(n = 10) |> 
  ggplot(aes(y = reorder(shooter, -prop), x = prop)) +
  geom_col(fill = "#E77500") +
  geom_label(aes(label = prop), size = 4, label.size = 0.5, fontface = "bold") +
  geom_text(aes(label = freq), x = 0.01, fontface = "bold") +
  geom_text(label = "shots", x = 0.035, fontface = "bold") +
  theme_bw() +
  labs(
    title = "",
    x = "Shooting Percentage",
    y = "Player",
    caption = "Minimum of 18 shot attempts
    
    Data Courtesy of Wehoop"
  )  +
  theme(plot.title = element_text(hjust = 0.5, face= "bold"),
        axis.text.x = element_text(size = 10, vjust = 0.65),
        axis.text.y = element_text(size = 10), 
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 15))


```



```{r}
wnba_shots2 <- wnba_pbp |> 
  filter(shooting_play) |> 
  # make a column to indicate the shooting team
  mutate(shooting_team = ifelse(team_id == home_team_id, 
                                home_team_name,
                                away_team_name)) |> 
  select(game_id, game_play_number, game_type = season_type,
         desc = text, shot_type = type_text, 
         made_shot = scoring_play, shot_value = score_value, 
         coordinate_x, coordinate_y, shooting_team, 
         home_team_name, away_team_name, home_score, away_score, qtr,
         quarter_seconds_remaining = start_quarter_seconds_remaining,
         game_seconds_remaining = start_game_seconds_remaining)

wnba_shots2 <- wnba_shots2 |> 
  filter(shooting_team %in% c("Seattle", "Chicago", "Washington", "Atlanta", "Minnesota", "Indiana", "Los Angeles", "Connecticut", "Dallas", "Phoenix", "New York", "Las Vegas")) |> 
  mutate(made_shot = ifelse(made_shot == "TRUE", 1, 0)) |> 
  mutate(
    # take the absolute value of the x coordinate to only get one side of the court
    coordinate_x = abs(coordinate_x),
    # rename shooting_team to include team name
    shooting_team = case_match(
      shooting_team,
      "Atlanta" ~ "Atlanta Dream",
      "Chicago" ~ "Chicago Sky",
      "Connecticut" ~ "Connecticut Sun",
      "Dallas" ~ "Dallas Wings",
      "Indiana" ~ "Indiana Fever",
      "Las Vegas" ~ "Las Vegas Aces",
      "Los Angeles" ~ "Los Angeles Spark",
      "Minnesota" ~ "Minnesota Lynx",
      "New York" ~ "New York Liberty",
      "Phoenix" ~ "Phoenix Mercury",
      "Seattle" ~ "Seattle Storm",
      "Washington" ~ "Washington Mystics"
    ),
    shooter = ifelse(
      str_detect(desc, "blocks") == TRUE,
      sub(
        ".*?\\b(?:blocks)\\W+(\\w+(?:\\W+\\w+){0,2})\\b(?:'s| 's| B. 's)\\s.*",
        "\\1",
        desc,
        perl = TRUE
      ),
      sub("\\ makes.*|\\ misses.*|\\ B. makes.*|\\ B. misses.*", "\\1", desc)
    )
  )

free_throw <- wnba_shots2[grep('Free Throw', wnba_shots2$shot_type),]

free_throw <- free_throw |> 
  select(game_type, made_shot, shooter) |>
  group_by(shooter) |>
  summarise(num_shots = n(),
            shots_made = sum(made_shot),
            shooting_perc = shots_made / num_shots) |>
  mutate(season = "Free Throw")

  
season <- wnba_shots |> 
  select(game_type, made_shot, shooter) |>
  group_by(shooter, game_type) |>
  summarise(num_shots = n(),
            shots_made = sum(made_shot),
            shooting_perc = shots_made / num_shots) |>
  mutate(season = ifelse(game_type == 2, "Regular Season", "Playoffs"))

shot_perc_table <- full_join(season, free_throw)

shot_avg_perc <- 0.44
  
shot_perc_table |> 
  filter(shooter == "A'ja Wilson") |> 
  ggplot(aes(shooter, shooting_perc, fill = season)) +
  geom_col(position = "dodge", color = "black") +
  geom_hline(yintercept = shot_avg_perc, size = 1, color = "purple2", linetype = "dashed") +
    labs(
    title = "",
    y = "Shooting Percentage",
    x = "Player",
    caption = "Regular Season Shooting Percentage: 0.44
    
    Data Courtesy of Wehoop",
    fill = "Shooting Percentage \nType"
  ) +
  scale_fill_manual(values = c("orange1", "lightblue2", "navyblue")) +
  theme(plot.title = element_text(hjust = 0.5, face= "bold"),
        axis.text.x = element_text(size = 10, vjust = 0.65),
        axis.text.y = element_text(size = 10), 
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 15))

```



```{r}
wnba_shots <- wnba_shots |> 
  mutate(time_group = game_seconds_remaining %/% 30)
```



```{r}

# Graph 1
wnba_shots |>
  filter(game_type == 2) |> 
  select(time_group, shooting_team, made_shot) |> 
  group_by(time_group, shooting_team) |> 
  summarise(num_shots = n(), 
            total_shots_made = sum(made_shot)) |> 
  mutate(prop = round(total_shots_made / num_shots, 3)) |>
  ggplot(aes(x = time_group, y = prop)) +
  geom_line(alpha = 0.4, color = "orange1") +
  geom_smooth(color = "#E77500", alpha = 0.2, se = FALSE) +
  geom_hline(yintercept = 0.44, color = "purple2", size = 1, linetype = "dashed") +
  facet_wrap(~ shooting_team) +
  scale_x_reverse() +
  scale_y_continuous(breaks = c(0.25, 0.5, 0.75)) +
  theme_bw() +
  labs(
    title = "Time Series of Goal Percentage in a Game (Regular Season)",
    x = "Game Time Remaining",
    y = "Shooting Percentage",
    caption = "Data Courtesy of Wehoop"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 16, hjust = 0.5, face= "bold"),
    axis.text.x = element_text(size = 10, vjust = 0.65),
    axis.text.y = element_text(size = 10), 
    axis.title = element_text(size = 15),
    strip.text = element_text(size = 12)
  )




# Graph 2
wnba_shots |> 
  filter(game_type == 3) |> 
  group_by(time_group, shooting_team) |> 
  summarise(num_shots = n(), 
            total_shots_made = sum(made_shot)) |> 
  mutate(prop = round(total_shots_made / num_shots, 3)) |> 
  ggplot(aes(x = time_group, y = prop)) +
  geom_line(alpha = 0.4, color = "orange1") +
  geom_smooth(color = "#E77500", alpha = 0.2, se = FALSE) +
  geom_hline(yintercept = 0.44, color = "purple2", size = 1, linetype = "dashed") +
  facet_wrap(vars(shooting_team)) +
  scale_x_reverse() +
  scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1), limits = c(0, 1)) +
  theme_bw() +
  labs(
    title = "",
    x = "Game Time Remaining", 
    y = "Shooting Percentage",
    caption = "Data Courtesy of Wehoop"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 16, hjust = 0.5, face= "bold"),
    axis.text.x = element_text(size = 10, vjust = 0.65),
    axis.text.y = element_text(size = 10), 
    axis.title = element_text(size = 15),
    strip.text = element_text(size = 15)
  )




# Graph 3
wnba_shots |> 
  filter(game_type == 2) |> 
  group_by(time_group, shooting_team) |> 
  summarise(num_shots = n()) |> 
  ggplot(aes(x = time_group, y = log(num_shots), color = shooting_team)) +
  geom_line(alpha = 0.4) +
  geom_smooth(alpha = 0.2, se = FALSE) +
  facet_wrap(vars(shooting_team)) +
  scale_x_reverse() +
  theme_bw() +
  labs(
    title = "Time Series of Shots in a Game (Regular Season)",
    x = "Game Time Remaining", 
    y = "Number of Shots",
    caption = "Data Courtesy of Wehoop"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 20, hjust = 0.5, face= "bold"),
    axis.text.x = element_text(size = 10, vjust = 0.65),
    axis.text.y = element_text(size = 10), 
    axis.title = element_text(size = 15),
    strip.text = element_text(size = 15)
  )




# Graph 4
wnba_shots |> 
  filter(game_type == 3) |> 
  group_by(time_group, shooting_team) |> 
  summarise(num_shots = n()) |> 
  ggplot(aes(x = time_group, y = log(num_shots), color = shooting_team)) +
  geom_line(alpha = 0.4) +
  geom_smooth(alpha = 0.2, se = FALSE) +
  facet_wrap(vars(shooting_team)) +
  scale_x_reverse() +
  theme_bw() +
  labs(
    title = "Time Series of Shots in a Game (Playoffs)",
    x = "Game Time Remaining", 
    y = "Number of Shots",
    caption = "Data Courtesy of Wehoop"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 20, hjust = 0.5, face= "bold"),
    axis.text.x = element_text(size = 10, vjust = 0.65),
    axis.text.y = element_text(size = 10), 
    axis.title = element_text(size = 15),
    strip.text = element_text(size = 15)
  )
  
```




```{r}
# Graph 1
wnba_shots |>
  filter(game_type == 3, shooting_team == "Las Vegas Aces") |> 
  select(time_group, shooting_team, made_shot) |> 
  group_by(time_group) |> 
  summarise(num_shots = n(), 
            total_shots_made = sum(made_shot)) |> 
  mutate(prop = round(total_shots_made / num_shots, 3)) |>
  ggplot(aes(x = time_group, y = prop)) +
  geom_line(alpha = 0.3, color = "orange1") +
  geom_line(stat = "smooth", alpha = 0.8, linewidth = 1.5, color = "#E77500") +
  # geom_smooth(alpha = 0.2, se = FALSE) +
  geom_hline(yintercept = 0.44, color = "purple2", size = 1, linetype = "dashed") +
  geom_text(aes(x = 42, y = shot_avg_perc, vjust = -0.5, hjust = 1), label = "Regular Season Shooting Percentage: 0.44") +
  # facet_wrap(~ shooting_team) +
  scale_x_reverse() +
  theme_bw() +
  labs(
    title = "Time Series of Shooting Percentage in Playoff Game",
    x = "Game Time Remaining",
    y = "Shooting Percentage",
    caption = "Data Courtesy of Wehoop"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, face= "bold")
  )


wnba_shots |> 
  filter(game_type == 2) |> 
  summarise(num_shots = n(),
         total_shots_made = sum(made_shot),
         shooting_perc = total_shots_made / num_shots)

```



```{r}
wnba_shots |>
  filter(game_type == 2, shooting_team == "Las Vegas Aces") |> 
  select(time_group, shooting_team, made_shot) |> 
  group_by(time_group) |> 
  summarise(num_shots = n(), 
            total_shots_made = sum(made_shot)) |> 
  mutate(prop = round(total_shots_made / num_shots, 3)) |>
  ggplot(aes(x = time_group, y = prop)) +
  geom_line(alpha = 0.3, color = "orange1") +
  geom_line(stat = "smooth", alpha = 0.8, linewidth = 1.5, color = "#E77500") +
  # geom_smooth(alpha = 0.2, se = FALSE) +
  geom_hline(yintercept = 0.44, color = "purple2", size = 1, linetype = "dashed") +
  geom_text(aes(x = 42, y = shot_avg_perc, vjust = -0.5, hjust = 1), label = "Regular Season Shooting Percentage: 0.44") +
  # facet_wrap(~ shooting_team) +
  scale_x_reverse() +
  theme_bw() +
  labs(
    title = "Time Series of Shooting Percentage in Playoff Game",
    x = "Game Time Remaining",
    y = "Shooting Percentage",
    caption = "Data Courtesy of Wehoop"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, face= "bold")
  )

```



## Clustering



```{r}
# Cluster 1

set.seed(87)


# creating new dataset
cluster_playoff <- wnba_shots |> 
  select(game_type, desc, made_shot, shooter) |> 
  filter(game_type == 3) |> 
  group_by(shooter) |> 
  summarise(freq = n(),
    total_shots_made = sum(made_shot)) |> 
  mutate(prop = round(total_shots_made / freq, 3))
  
# normalizing the data
cluster_playoff <- cluster_playoff |> 
  mutate(
    std_shot_made = as.numeric(scale(total_shots_made, center = TRUE, scale = TRUE)),
    std_shots = as.numeric(scale(freq, center = TRUE, scale = TRUE))
  )

std_kmeans <- cluster_playoff |> 
  select(std_shot_made, std_shots) |> 
  kmeans(algorithm = "Lloyd", centers = 3, nstart = 30)

cluster_playoff |>
  mutate(
    player_clusters = as.factor(std_kmeans$cluster)
  ) |>
  ggplot(aes(x = std_shot_made, y = std_shots,
             color = player_clusters)) +
  geom_point(size = 2, alpha = 0.5) + 
  ggthemes::scale_color_colorblind() +
  theme(legend.position = "bottom") +
  coord_fixed() +
  theme_bw() +
  labs(
    x = "Total Shots Made",
    y = "Shots Attempted",
    color = "Player Clusters",
    title = "Impact Players in Playoffs",
    caption = "Data Courtesy of Wehoop"
  ) +
   theme(
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5, face= "bold")
  )







# creating new dataset
cluster_playoff2 <- wnba_shots |> 
  select(game_id, game_type, desc, made_shot, shot_value, shooter) |> 
  filter(game_type == 3) |> 
  group_by(shooter, game_id) |> 
  summarise(freq = n(),
    total_shots_made = sum(made_shot),
    prop = total_shots_made / freq,
    total_points = sum(shot_value),
    point_perc = total_points / freq) |>
  mutate(prop = round(total_shots_made / freq, 3),
         games = 1) |> 
  group_by(shooter) |>
  summarise(gp = sum(games),
            total_shots_made = sum(total_shots_made),
            total_shots = sum(freq),
            shot_perc = total_shots_made / total_shots,
            total_points = sum(total_points),
            pts_per_game = total_points / gp)
  



## Cluster 2
# normalizing the data
cluster_playoff2 <- cluster_playoff2 |> 
  mutate(
    std_points = as.numeric(scale(total_points, center = TRUE, scale = TRUE)),
    std_shots = as.numeric(scale(total_shots, center = TRUE, scale = TRUE))
  )

std_kmeans2 <- cluster_playoff2 |> 
  select(std_points, std_shots) |> 
  kmeans(algorithm = "Lloyd", centers = 3, nstart = 30)

cluster_playoff2 |>
  mutate(
    player_clusters = as.factor(std_kmeans2$cluster)
  ) |>
  ggplot(aes(x = std_points, y = std_shots,
             color = player_clusters)) +
  geom_point(size = 2, alpha = 0.5) + 
  ggthemes::scale_color_colorblind() +
  theme(legend.position = "bottom") +
  coord_fixed() +
  theme_bw() +
  labs(
    x = "Total Points",
    y = "Shots Attempted",
    color = "Player Clusters",
    title = "Impact Players in Playoffs",
    caption = "Data Courtesy of Wehoop"
  ) +
   theme(
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5, face= "bold")
  )








## Cluster 3
  
cluster_playoff2 <- cluster_playoff2 |> 
  mutate(
    std_ppg = as.numeric(scale(pts_per_game, center = TRUE, scale = TRUE)),
    std_shot_perc = as.numeric(scale(shot_perc, center = TRUE, scale = TRUE))
  )

std_kmeans2 <- cluster_playoff2 |> 
  select(std_ppg, std_shot_perc) |> 
  kmeans(algorithm = "Lloyd", centers = 3, nstart = 30)

cluster_playoff2 |>
  mutate(
    player_clusters = as.factor(std_kmeans2$cluster)
  ) |>
  ggplot(aes(y = std_ppg, x = std_shot_perc,
             color = player_clusters)) +
  geom_point(size = 2, alpha = 0.5) + 
  ggthemes::scale_color_colorblind() +
  theme(legend.position = "bottom") +
  coord_fixed() +
  theme_bw() +
  labs(
    x = "Shooting Precentage",
    y = "Points Per Game",
    color = "Player Clusters",
    title = "Impact Players in Playoffs",
    caption = "Data Courtesy of Wehoop"
  ) +
   theme(
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5, face= "bold")
  )


# function to perform clustering for each value of k
gapminder_kmeans <- function(k) {
  
  kmeans_results <- cluster_playoff2 |>
    select(std_ppg, std_shot_perc) |>
    kmeans(centers = k, nstart = 30)
  
  kmeans_out <- tibble(
    clusters = k,
    total_wss = kmeans_results$tot.withinss
  )
  return(kmeans_out)
}

# number of clusters to search over
n_clusters_search <- 2:12

# iterate over each k to compute total wss
kmeans_search <- n_clusters_search |> 
  map(gapminder_kmeans) |> 
  bind_rows()

kmeans_search |> 
  ggplot(aes(x = clusters, y = total_wss)) +
  geom_line() + 
  geom_point(size = 4) +
  scale_x_continuous(breaks = n_clusters_search)


```





```{r}
# Probably dont need this

# wnba_shots2 |> 
#   filter(game_type == 3) |> 
#   group_by(shooting_team) |> 
#   summarise(total_shot_value = sum(shot_value)) |> 
#   mutate(shooting_team = fct_reorder(shooting_team, total_shot_value)) |> 
#   ggplot(aes(x = shooting_team, y = total_shot_value)) +
#   geom_col(aes(fill = shooting_team)) +
#   theme_bw() + 
#   geom_label(aes(label = total_shot_value), size = 3) + 
#   geom_text(aes(label = shooting_team), size = 3, vjust = 5, check_overlap = TRUE) +
#   labs(
#     title = "New York and Vegas Scoring More",
#     x = "Teams", 
#     y = "Total Shot Values",
#     fill = "Teams",
#     caption = "Data Courtesy of Wehoop"
#   ) + 
#   theme(axis.text.x=element_blank(),
#         axis.ticks.x=element_blank())
```

