# Team Colors

```{r}
scale_fill_manual(values = c("#C8102E", "#418FDE", "#643335", "#C4D600", "#FFCD00", "#000000", "#702F8A", "#236192", "#003DA5","#CB6015","#2C5234", "#0C2340")
```

```{r}
# wnba_shots <- wnba_shots |>
#   group_by(shooting_team) |>
#   mutate(
#     home_or_away = if_else(shooting_team == home_team_name, "Home", "Away"),
#     distance = as.numeric(str_extract(desc, "\\d{2}")),
#     attempted_point_value = if_else(
#       str_detect(desc, "[Ff]ree [Tt]hrow"), 1,
#       if_else(
#         str_detect(desc, "three point") | (distance > 21 & !is.na(distance)), 3, 2
#       )
#     )
#   )

# 
# View(wnba_shots)
# 
# wnba_shots |> 
#  filter(shot_value != attempted_point_value & shot_value > 0) |>
#   select(shooting_team, desc, shot_value, attempted_point_value)

```

```{r}
# wnba_shots |>
#   select(shooting_team, home_or_away, attempted_point_value, shot_value) |>
#   group_by(shooting_team, home_or_away, shot_value, attempted_point_value) |>
#   summarise(count = n())
#   


color_vector <- c("firebrick4", "firebrick", "firebrick3", "firebrick2", "firebrick1", "darkorange1", "goldenrod1", "gold", "lightgreen", "green1","green3", "green4", "darkgreen"))

levels(close_games_observing$out)
```

## Games With Close Scores (6 points or less) At Some Point In The Last 30 Seconds

```{r}
# End of game shots where the score differential was less than 6 after the shot was taken
end_of_game_shots <- wnba_shots |>
  filter(game_seconds_remaining <= 30 & score_differential %in% c(-6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6)) 


# Games That Had A Close Score At Some Point Within the last 30 seconds; The highest time where a shot occurred
close_games <- end_of_game_shots |> 
  group_by(game_id) |> 
  slice_max(game_seconds_remaining) |> 
  arrange(-free_throw) |> 
  slice_head() |>
  select(game_id, home_team_name, away_team_name, score_differential)


# The last shot of the every game 
final_score <- wnba_shots |> 
  group_by(game_id) |> 
  slice_min(game_seconds_remaining) |> 
  arrange(free_throw) |> 
  slice_head() |> 
   rename(final_score_differential = score_differential) |> 
   select(game_id, final_score_differential)

# Score Change From First Shot In Last 30 Seconds Where Score is 
close_games_observing <- left_join(close_games, final_score) |> 
  mutate(home_team_outcome =  
 if_else(score_differential > 0 & final_score_differential > 0 & score_differential == final_score_differential, "Kept Same Lead",
 if_else(score_differential > 0 & final_score_differential > 0 & score_differential > final_score_differential, "Kept Lead - Decreased",
 if_else(score_differential > 0 & final_score_differential > 0, "Kept Lead - Increased",
 if_else(score_differential > 0 & final_score_differential == 0, "Lost Lead - Tied", 
 if_else(score_differential > 0 & final_score_differential < 0, "Lost Lead - Lost", 
 if_else(score_differential < 0 & final_score_differential < 0 & score_differential == final_score_differential, "No Comeback",
 if_else(score_differential < 0 & final_score_differential < 0 & score_differential > final_score_differential, "Comeback - Not Enough",
 if_else(score_differential < 0 & final_score_differential < 0 & final_score_differential > score_differential, "No Comeback - Deficity Increased",
 if_else(score_differential < 0 & final_score_differential == 0, "Comeback - Tied",
 if_else(score_differential == 0 & final_score_differential == 0, "No Comeback - Tied",
 if_else(score_differential == 0 & final_score_differential > 0, "Took Lead From Tie",
 if_else(score_differential == 0 & final_score_differential < 0, "Lost From Tie", 
         "Took Lead")))))))))))))

close_games_observing


```

## Overtime

```{r}
# End of game shots where the score differential was less than 6 after the shot was taken
end_of_game_shots <- wnba_shots |>
  filter(game_seconds_remaining <= 30 & score_differential %in% c(-6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6)) 


# Games That Had A Close Score At Some Point Within the last 30 seconds; The highest time where a shot occurred
close_games <- end_of_game_shots |> 
  group_by(game_id) |> 
  slice_min(game_play_number) |> 
  slice_head() |>
  select(game_id, home_team_name, away_team_name, score_differential)


# The last shot of the every game 
final_score <- wnba_shots |> 
  group_by(game_id) |> 
  slice_max(game_play_number) |> 
  slice_head() |> 
   rename(final_score_differential = score_differential) |> 
   select(game_id, final_score_differential)
```

# Side By Side Win vs. Losses Home Versus Away

```{r}
# Away Results In Close Games
away_win_loss <- win_losses |> 
  group_by(away_win_or_loss) |> 
  summarise(occurances = n()) 


#away_win_loss

# Home Results In Close Games
home_win_losses <- win_losses |> 
  group_by(home_win_or_loss) |> 
  summarise(occurances = (n())) 

#home_win_losses

# Graph of Away Team Win vs. Loss Proportion
away_win_vs_losses <- ggplot(away_win_loss, aes(x = away_win_or_loss, y = occurances)) +
  geom_bar(stat = "identity", aes(fill = away_win_or_loss)) +
  scale_fill_manual(values = c("firebrick", "goldenrod1", "green4")) +
  theme(legend.position = "none",
        axis.title.y = element_blank()) +
  labs(title = "Away Team's Outcome In Close Games",
       x = "Outcome") +
  geom_label(aes(label = occurances), position = position_stack(vjust = 0.5)) 

#away_win_vs_losses

# Graph of Home Team Win vs. Loss Proportion
home_win_vs_losses <- ggplot(home_win_losses, aes(x = home_win_or_loss, y = occurances)) +
  geom_bar(stat = "identity", aes(fill = home_win_or_loss)) +
  scale_fill_manual(values = c("firebrick", "goldenrod1", "green4")) +
  theme(legend.position = "none") +
  geom_label(aes(label = occurances), position = position_stack(vjust = 0.5)) +
  labs(title = "Home Team's Outcome In Close Games",
       x = "Outcome",
       y = "Occurances")

#home_win_vs_losses

library(patchwork)

home_win_vs_losses + away_win_vs_losses + 
   plot_layout(guides = "collect") 
```

# Wrangled Data

## Outcomes Occured Across Leagues In Close Games

```{r, include=FALSE}
# Adds Both Away And Home Win vs. losses
win_losses <- close_games_observing |>
  pivot_longer(Home_Result:Away_Result,
               values_to = "win_or_loss",
               names_to = "home_or_away_result") |> 
  pivot_longer(home_team_name:away_team_name,
               values_to = "teams",
               names_to = "home_or_away_team") |> 
  mutate(home_or_away_result = ifelse(home_or_away_result == "Home_Result", "Home", "Away"),
         home_or_away_team = ifelse(home_or_away_team == "home_team_name", "Home", "Away"))
         
win_losses
```


# Related To Win vs. Loss Types Home and Away Per Team
```{r}
possible_outcomes2 <- full_join(home_game_results, possible_outcomes1)

possible_outcomes2

close_games_observing |> 
  filter(home_team_name == "Atlanta") |> 
  full_join()

close_games_observing |> 
  filter(away_team_name == "Atlanta")

# Number of Occurences of All Outcomes For Home vs. Away
possible_outcomes2 <- full_join(home_game_results, away_game_results, by = "outcome") |> 
  ungroup()|> 
  mutate(num_times_home_per_team = replace_na(num_times_home_per_team, 0),
         times_occured_away_per_team = replace_na(times_occured_away_per_team, 0),
         Win_Loss = ifelse(is.na(Away_Result), Home_Result, Away_Result)) |> 
  select(-Home_Result, -Away_Result) |> 
  group_by(home_team_name, num_times_home_per_team)

possible_outcomes2

|> 
  ungroup()|> 
  mutate(num_times_home_per_team = replace_na(num_times_home_per_team, 0),
         times_occured_away_per_team = replace_na(times_occured_away_per_team, 0),
         Win_Loss = ifelse(is.na(Away_Result), Home_Result, Away_Result)) |> 
  select(-Home_Result, -Away_Result) |> 
  group_by(home_team_name, num_times_home_per_team)

possible_outcomes2
```


# Team Outcome Type Home vs. Away
```{r}
# All Possible Outcomes
possible_outcomes1 <- data.frame(outcome = c("Won - Kept Same Lead", "Won - Lead Decreased", "Won - Extended Lead", "Tied - Lost Lead", "Lost - Lost Lead", "Lost - No Comeback", "Lost - Deficit Increased", "Lost - Deficit Decreased", "Tied - Comeback", "Tied - No Change", "Won - From Tie", "Lost - From Tie", "Won - Took Lead From Loss"),
                                 Home_Result = c("Win", "Win", "Win", "Tie", "Loss", "Loss", "Loss", "Loss", "Tie", "Tie", "Win", "Loss", "Win")) 

#possible_outcomes1


# Atlanta's Home Outcomes
Atlanta <- home_game_results |> 
  filter(home_team_name == "Atlanta")

Atlanta

Atlanta_final <- full_join(Atlanta, possible_outcomes1) |> 
  mutate(num_times_home_per_team = replace_na(num_times_home_per_team, 0),
         home_team_name = replace_na(home_team_name, "Atlanta")) |> 
  ungroup()

Atlanta_final


# Including All Outcomes
Atlanta_home_outcomes <- Atlanta_final |> 
  ggplot(aes(x = Home_Result, y = num_times_home_per_team, fill = outcome)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Occurences of Each Outcome Type For Home Teams",
       y = "Occurences",
       fill = "Outcome") +
  scale_fill_manual(values = win_loss_color_vector) +
  theme(axis.title.x = element_blank()) 

Atlanta_home_outcomes

```

